version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Building application..."
      - npm install
      - npm run build
      - zip -r build.zip .
  post_build:
    commands:
      - echo "Uploading build artifacts to S3..."
      - aws s3 cp build.zip s3://suica-onedetail-bucket/build/

artifacts:
  files:
    - build.zip
