name: Manual Deploy to AWS CodePipeline

on:
  workflow_dispatch:  # これを追加すると、GitHub UI から手動実行可能

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Trigger AWS CodePipeline
        run:  aws codepipeline start-pipeline-execution --name scAwsPipeline
